# Generated by Django 4.0.1 on 2022-01-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='raitingAuthor',
            new_name='ratingAuthor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='raiting',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='raiting',
            new_name='rating',
        ),
    ]
